### ISSUE TITLE
Configurable means to add additonal secrets

### ISSUE THREAD

**Issue by okyspace** [allegroai/clearml-helm-charts#161]
There are cases where we need to add credentials (e.g.s3) as secret for our server and agent. Currently need to addon through clearml-secrets instead of adding on in override.yaml. 

Probably can consider to populate the additional secrets in clearml-secrets.yaml when we define the credentials in override.yaml. else a separate xxz-secrets.yaml if it is cleaner.

**Comment by valeriano-manassero** [comment]
I'm not sure I get what you mean in your proposal.

Can you write down a small example on override file and expected result pls?

**Comment by okyspace** [comment]
e.g. in override.yaml 
```
extraSecrets:
  - name: s3-credentials
    access_key: xxxx
    secret_key: yyy
- name: next secret
   user: zzz
   password: ppp
- name: .....
```

Expected to see this populate in clearml-secret.yaml like
```
<existing secrets>
---apiVersion: v1
kind: Secret
metadata: 
  name: s3-credentials
type: Opaque
data: 
  access_key: xxx
  secret_key: yyy
----
<next secret>
```
