### ISSUE TITLE
Queue doesn't created automatically on agent chart

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#170]
```
enterpriseFeatures:
    queues:
      g-2:
        templateOverrides:
          resources:
            limits:
              nvidia.com/gpu: 2
              memory: 16G
            requests:
              nvidia.com/gpu: 2

      g-1:
        templateOverrides:
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 12G
            requests:
                nvidia.com/gpu: 1

```
when we create the agent chart the queue should be created automatically by the chart 
in this version it doesn't and  the glue agent failing to start
