### ISSUE TITLE
After upgrade to the new chart version error 

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#193]
Hey i tried to install both of the sub charts agent and server under "my chart" umbrella 

(did not  added any nameoveride the the subcharts)

```
dependencies:
  - name: clearml
    version: 6.0.2
    repository: '@blabla'
  - name: clearml-agent
    version: 4.0.2
    repository: '@blabla'
```

got the following error:

`Error: INSTALLATION FAILED: Deployment.apps "clearml-clearml-agent" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"clearml", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"clearml-clearml-agent", "app.kubernetes.io/version":"1.24", "helm.sh/chart":"clearml-agent-4.0.2"}: `selector` does not match template `labels``
