### ISSUE TITLE
Resouces in the values file for agentk8sglue-deployment

### ISSUE THREAD

**Issue by tkraan** [allegroai/clearml-helm-charts#229]
Because our environment does not allow us to run pods without resources we would like to have a extra resources tag in the values file of the agent.

At the moment I have included the following resources in the template for the init and k8s-glue container.

```yaml
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"     
```
