### ISSUE TITLE
Fix init container waits forever pinging a redis in production config

### ISSUE THREAD

**Issue by LukasBommes** [allegroai/clearml-helm-charts#240]
### Describe the bug a clear and concise description of what the bug is.

I encountered the same bug as solved here (https://github.com/allegroai/clearml-helm-charts/pull/178), but for redis instead of mongodb

### What's your helm version?

version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.26) and server (1.22) exceeds the supported minor version skew of +/-1

### What's the chart version?

7.2.2

### Enter the changed values of values.yaml?

```
apiserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: "api.clearml.myurl.lan"
fileserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: "files.clearml.myurl.lan"
  storage:
    data:
      class: csi-rbd-sc
      size: 250Gi
webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: "app.clearml.myurl.lan"
redis:
  master:
    persistence:
      storageClass: csi-rbd-sc
mongodb:
  persistence:
    storageClass: csi-rbd-sc
elasticsearch:
  volumeClaimTemplate:
    storageClassName: csi-rbd-sc
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      ingest.geoip.downloader.enabled: false
```

**Comment by LukasBommes** [comment]
I now adopted the suggested production values.yaml and found that also the probe for elasticsearch goes to the wrong service. It should go to `http://clearml-elastic-master-headless:9200/_cluster/health` instead of `http://clearml-elastic-master:9200/_cluster/health`.

These are the values.yaml for reproducing:

```
apiserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: "api.clearml.myurl.lan"

fileserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: "files.clearml.myurl.lan"
  storage:
    data:
      class: csi-rbd-sc
      size: 250Gi

webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: "app.clearml.myurl.lan"

redis:
  master:
    name: clearml-redis
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      storageClass: csi-rbd-sc
  replica:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      storageClass: csi-rbd-sc
  architecture: replication

mongodb:
  enabled: true
  architecture: replicaset
  replicaCount: 2 #3
  arbiter:
    enabled: false
  pdb:
    create: true
  podAntiAffinityPreset: soft
  persistence:
    storageClass: csi-rbd-sc

elasticsearch:
  replicas: 2 #3
  volumeClaimTemplate:
    storageClassName: csi-rbd-sc
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      ingest.geoip.downloader.enabled: false
```
