### ISSUE TITLE
[clearml-agent] Wrong nindent for agentk8sglue-deployment template

### ISSUE THREAD

**Issue by andreimahu** [allegroai/clearml-helm-charts#262]
### Describe the bug a clear and concise description of what the bug is.

At line number 77 the nindent should be 12 instead of 10
https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-agent/templates/agentk8sglue-deployment.yaml#L77

### What's your helm version?

irrelevant

### What's your kubectl version?

irrelevant

### What's the chart version?

5.1.1

### Enter the changed values of values.yaml?

```
agentk8sglue:
  volumeMounts:
    - mountPath: /mnt/secrets-store
      name: secrets-store-inline
      readOnly: true
```
