### ISSUE TITLE
[clearml-agent] CLEARML_AGENT_GIT_* Environment variables are empty on the worker pod

### ISSUE THREAD

**Issue by andreimahu** [allegroai/clearml-helm-charts#263]
### Describe the bug a clear and concise description of what the bug is.

When setting agentk8sglue.basePodTemplate.env CLEARML_AGENT_GIT_USER and CLEARML_AGENT_GIT_PASS end up as being set to an empty value on the launched worker pod. Other env vars set there are properly provisioned. For example, the backwards compatible TRAINS_AGENT_GIT_USER and TRAINS_AGENT_GIT_PASS are set correctly and are a workaround for the moment. The configmap generated from the basePodTemplate is correct in k8s and also looks fine inside the k8s glue pot itself (template/template.yaml). So something seems to go wrong when k8s glue is parsing the template.yaml file.

### What's your helm version?

irrelevant

### What's your kubectl version?

irrelevant

### What's the chart version?

5.1.1

### Enter the changed values of values.yaml?

```
agentk8sglue:
  basePodTemplate:
    env:
      - name: CLEARML_AGENT_GIT_USER
         value: "some-git-username"
      - name: CLEARML_AGENT_GIT_PASS
         valueFrom:
           secretKeyRef:
             name: my-git-secret
             key: git-pass
```
