### ISSUE TITLE
[clearml-agent] existingAgentk8sglueSecret ignored by Deployment template

### ISSUE THREAD

**Issue by savitha-qs** [allegroai/clearml-helm-charts#275]
### Describe the bug a clear and concise description of what the bug is.

The `Deployment` template (in `agentk8sglue-deployment.yaml`) in the `clearml-agent` chart ignores the `clearml.existingAgentk8sglueSecret` setting in the `values.yaml` file. 

```
            - name: CLEARML_API_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "clearmlAgent.fullname" . }}-ac
                  key: agentk8sglue_key
            - name: CLEARML_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "clearmlAgent.fullname" . }}-ac
                  key: agentk8sglue_secret
```

The name of the `secretKeyRef` should be conditional based on `existingAgentk8sglueSecret` similar to how the `ConfigMap` template (in `agentk8sglue-configmap.yaml`) does it.

```
            - name: CLEARML_API_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.clearml.existingAgentk8sglueSecret }}
                  name: {{ .Values.clearml.existingAgentk8sglueSecret }}
                  {{- else }}
                  name: {{ include "clearmlAgent.fullname" . }}-ac
                  {{- end }}
                  key: agentk8sglue_key
            - name: CLEARML_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.clearml.existingAgentk8sglueSecret }}
                  name: {{ .Values.clearml.existingAgentk8sglueSecret }}
                  {{- else }}
                  name: {{ include "clearmlAgent.fullname" . }}-ac
                  {{- end }}
                  key: agentk8sglue_secret
```

### What's your helm version?

3.11.1

### What's your kubectl version?

1.27.1

### What's the chart version?

5.1.3

### Enter the changed values of values.yaml?

NONE
