### ISSUE TITLE
Unable to deploy clearml-agent in k8s (EKS)

### ISSUE THREAD

**Issue by surya9teja** [allegroai/clearml-helm-charts#281]
I am using the fluxcd (gitops) to deploy the helm release of clearml-agent and it seems there is an issue with accessing api server. 
Error
`clearml_agent.backend_api.session.session.LoginError: Failed getting token (error 401 from https://api.clear.ml): Unauthorized (invalid credentials) (failed to locate provided credentials)`

The fluxcd helmrelase yaml file 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: clearml-agent
  namespace: dev
spec:
  interval: 30s
  releaseName: clearml-agent-dev
  chart:
    spec:
      chart: clearml-agent
      version: "5.1.4"
      sourceRef:
        kind: HelmRepository
        name: clearml
        namespace: flux-system
  values:
    clearml:
      existingAgentk8sglueSecret: clearml-agent-secret
    agentk8sglue:
      queue: dev,nvidia-dev
      extraEnvs:
        - name: CLEARML_API_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: clearml-agent-secret
              key: agentk8sglue_key
        - name: CLEARML_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: clearml-agent-secret
              key: agentk8sglue_secret
```

If anyone made it to deploy this, help me. 
Am I missing something here in values? 
Also it seems the current docker images is using old python version. Any plans to update it? I don't mind to do a PR but before that I need to figure out the current issue.
