### ISSUE TITLE
[clearml] Support for Other DB Types

### ISSUE THREAD

**Issue by Hammad-NobleAI** [allegroai/clearml-helm-charts#303]
### Is your feature request related to a problem ?

I attempted to install the ClearML Server on a Docker Desktop cluster on my M1 Mac, but the MongoDB pod kept crashing because of this [issue](https://github.com/bitnami/containers/issues/53407). It appeared that the solution to that involved modifying the `values.yaml` file to add an environment variable which forced Docker to use QEMU: https://github.com/bitnami/containers/issues/40947#issuecomment-1968364385. However, the database still seemed unable to start up, and indeed, Bitnami has confirmed that they currently do not support ARM as MongoDB upstream does not support Debian on ARM: https://github.com/bitnami/containers/issues/67962#issuecomment-2180470456

### Describe the solution you'd like.

Would it be possible to support alternative databases like MySQL or Postgres?

### Describe alternatives you've considered.

Considered trying to modify the helm chart locally to work with an alternative db container, but I'll need to become more proficient with K8/helm before I can do this.

**Comment by valeriano-manassero** [comment]
Hi,
there are two ways to overcome this limitation:
first option is to turn on `Use Rosetta for x86_64/amd64 emulation on Apple Silicon` on Docker Desktop settings.

Otherwise you need to use a Mongo arm image using following override during chart deployment:
```
mongodb:
  image:
    repository: arm64v8/mongo
    tag: latest
  persistence:
    mountPath: /data/db
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
```
