### ISSUE TITLE
clearml-agent deployed with the latest Helm chart ignores docker parameters

### ISSUE THREAD

**Issue by stefano-cherchi** [allegroai/clearml-helm-charts#58]
Just upgraded my clearml-server on Kubernetes to the latest version of the chart:

```
$ helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
clearml-server          default         4               2022-03-29 18:42:34.558007 +0200 CEST   deployed        clearml-3.8.0                   1.3.0      
```

Until yesterday I've been using a very old version:

```
repository = "https://allegroai.github.io/clearml-server-helm"
chart      = "clearml-server-chart"
version    = "1.0.2+1"
```

In the old version, the agents were configured as follows:

```
agent:
  numberOfClearmlAgents: 2
  nvidiaGpusPerAgent: 0
  defaultBaseDocker: "python:3.8-bullseye"
  dockerMode: true
  agentVersion: "" # if set, it *MUST* include comparison operator (e.g. ">=0.17.2")
  queues: "default"
  
[...]
```

Since I use cv2 in some of my experiments, the execution would initially fail with this error:

`ImportError: libGL.so.1: cannot open shared object file: No such file or directory
`

But I could easily solve the issue by just adding this 

`apt update && apt install -y libgl1-mesa-glx
`

In the web UI in the field `Execution -> Container -> SETUP SHELL SCRIPT`

<img width="352" alt="image" src="https://user-images.githubusercontent.com/3993552/160782956-0ddd9300-0185-4f35-a75a-62c51324421c.png">

Now, in the new deployment, the agents are configured as follows:

```
agentGroups:
  agent-group-cpu:
    enabled: true
    name: agent-group-cpu
    replicaCount: 2
    updateStrategy: Recreate
    nvidiaGpusPerAgent: 0
    agentVersion: ""  # if set, it *MUST* include comparison operator (e.g. ">=0.16.1")
    queues: "default"  # multiple queues can be specified separated by a space (e.g. "important_jobs default")

    [...]

    image:
      repository: "python"
      pullPolicy: IfNotPresent
      tag: "3.8-bullseye"

    podAnnotations: {}

    nodeSelector: 
      app: "services"

    tolerations: []

    affinity: {}
```

The problem is, now the command `apt install` in the field `SETUP SHELL SCRIPT` seems to be completely ignored.

**Comment by valeriano-manassero** [comment]
Hi @stefano-cherchi ,
actually the K8s installation chart we have here is spawning agent groups during Helm install and we are not spawning new Docker containers when a new task is submitted. I think this is the point in time where `SETUP SHELL SCRIPT` is called so we are never there with K8s.

First suggestion that comes to my mind is to use a different image configuration in agent group like:
```
    image:
      repository: "dkimg/opencv"
      pullPolicy: IfNotPresent
      tag: "4.3.0-debian"
```

If I'm not wrong this image already contains a working set for opencv.

Let me know if this works for you.

/cc @jkhenning do you have better solutions in mind?
